### ISSUE TITLE
баг навбара 2

### ISSUE THREAD

**Issue by smertlove** [bmstu-iu9/ptp2021-1-dictionary#12]
когда mySuggestions на экране, кнопка navbar-toggler-icon во время анимации перекрывает mySuggestions, а иногда перестает работать вообще

**Comment by Lasadaf** [comment]
варианты теперь сверху, но у меня кнопка не глючит, так что я не знаю, что чинить

**Comment by smertlove** [comment]
во время открытия перекрывает mySuggestions. Выглядит некрасиво


<img width="442" alt="баг навбара 2" src="https://user-images.githubusercontent.com/81481516/127916591-7b077c24-ace8-4345-b08c-2cdabd16be10.png">

**Comment by Lasadaf** [comment]
¿?
![bandicam 2021-08-03 00-13-54-982](https://user-images.githubusercontent.com/86784572/127924873-8152b7d0-46c2-4344-b5a2-ed188b6fe07a.jpg)

**Comment by smertlove** [comment]
открой и закрой ее, когда в mySuggestions есть что-то

**Comment by Lasadaf** [comment]
вы в dev смотрите? ширина на скрине меньше (АДА вообще с переносом), чем я ставил в dev. когда я в ветке filter добавлял те же стили, всё работало, и кнопка не глючила.

**Comment by smertlove** [comment]
да, вроде, все теперь нормально работает. Закрываю issue
