### ISSUE TITLE
баг всего сайта при попадании в мейн

### ISSUE THREAD

**Issue by smertlove** [bmstu-iu9/ptp2021-1-dictionary#21]
15 минут назад залили dev в main для того, чтобы посмотреть, не заработала ли адаптивность. Адаптивность не заработала + увидели вот такие страшные вещи.

![bug1](https://user-images.githubusercontent.com/81481516/128372413-3faa65a5-4415-4fe2-bdca-ce19bef223c6.jpg)

этот вопрос надо решать.

**Comment by emrzvv** [comment]
при запуске на локальной машине всё норм, видимо, проблемы с подключением навбара. в stroka.html менялась структура html, возможно, в связи с этим вызвана проблема

**Comment by smertlove** [comment]
но ведь наш css тоже пропадает. А бутстрапий остается whatsoever

**Comment by smertlove** [comment]
I assume you followed the documentation? Have you got an email?- From the 404: "We'll send you an email when your page has been built. It may take up to ten minutes until your page is available."  -- цитата со stackoverflow. Пишет, что просто подождать надо.

**Comment by smertlove** [comment]
мб в этом проблема

**Comment by Lasadaf** [comment]
зачем мейн тогда откатили?

**Comment by smertlove** [comment]
исправили путем замены ссылок
