### ISSUE TITLE
футер и навбар

### ISSUE THREAD

**Issue by smertlove** [bmstu-iu9/ptp2021-1-dictionary#34]
навбар снова не sticky, а footer перекрывает кнопки на exercise_list_page
![123123123](https://user-images.githubusercontent.com/81481516/128700143-d67d3167-0fa0-4ee6-9182-4ff33b265a80.jpg)

**Comment by Lasadaf** [comment]
сделаю

**Comment by Lasadaf** [comment]
сделал

**Comment by Mazdaywik** [comment]
Вы бы указывали pull request, который исправил эту ошибку. Или в сам коммит добавили бы #34.
