### ISSUE TITLE
Ссылки не кликаются

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/ptp2021-1-dictionary#7]
Открыл страницу

<https://bmstu-iu9.github.io/ptp2021-1-dictionary/searchpage>.

Вижу вот такой красивый сайт:

![image](https://user-images.githubusercontent.com/1309859/126309994-0f036ca2-082e-45ed-9567-524af7ae19ad.png)

Но ни одна из ссылок на нём не работает.

Это сейчас так и должно быть?

**Comment by smertlove** [comment]
Да. Наш Index пока что не рабочий + шапки на всех страницах старые. Все тренажеры (со страницы exercise_list_page) пока что в прототипном состоянии (скрипты работают, но никаких статистик и всего прочего там пока нет)

**Comment by smertlove** [comment]
Мы торопились залить в мейн

**Comment by Mazdaywik** [comment]
Страница <https://bmstu-iu9.github.io/ptp2021-1-dictionary/pages/exercise_page.html?task=fill&lang=eng> работает неплохо.

Также нужно добавить `index.html`, а то по ссылке `https://bmstu-iu9.github.io/ptp2021-1-dictionary` пока отображается по умолчанию `README.md`.

**Comment by smertlove** [comment]
searchpage -- наш индекс. Переименуем

**Comment by Mazdaywik** [comment]
`git mv …`

**Comment by smertlove** [comment]
Перезайдите с exercise_list_page, там можно выбрать 
больше заданий

**Comment by smertlove** [comment]
хорошо

**Comment by Mazdaywik** [comment]
> Перезайдите с exercise_list_page, там можно выбрать
> больше заданий

А я оттуда и перешёл на `pages/exercise_page.html`.

**Comment by Mazdaywik** [comment]
Как только код появился в `main`, сразу посчитался вклад участников:

https://github.com/bmstu-iu9/ptp2021-1-dictionary/graphs/contributors

И у первых трёх (@smertlove, @Lasadaf, @polinasam12) вклад выглядит довольно неплохо. Надеюсь, со временем там появится и вклад остальных членов команды.

**Comment by smertlove** [comment]
Ларионову сегодня дал много заданий, основываясь на этих графиках. Поршенко еще не доделал свое задание с прошлой недели (карточки) + на этой я ему поручил писать парсер для того, чтобы можно было доставать озвучку для слов. Самохвалова тоже получила какое-то количество заданий для того, чтобы улучшить график. Степанов и я на этой неделе почти не работаем тк заданий пока что не осталось (появятся, когда представим первую рабочую версию сайта Бутенко). К слову, у меня появился один вопрос. Сейчас напишу Вам на почту

**Comment by smertlove** [comment]
К слову, Поршенко верстал шапку, но в силу определенных причин его вклад не отразился в графиках.

**Comment by Mazdaywik** [comment]
Прочитаю письмо вечером, сейчас я с рабочего компьютера. Также вечером посмотрю, почему вклад Поршенко не отобразился.

**Comment by Mazdaywik** [comment]
Вклад Егора не отразился на графиках из-за того, что его ветка (ещё) не влита в `main`. Вот она, отдельно растёт:
![image](https://user-images.githubusercontent.com/1309859/126370779-5c20084d-7434-48d8-8266-9fbe4e8c49f9.png)
